name: Test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2.0.3
      with:
        channel: 'stable'

    - run: flutter pub get
    - run: flutter format --set-exit-if-changed .
    - run: flutter analyze .
    - run: flutter test
